// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemoteControllerMaster.Database;

#nullable disable

namespace RemoteControllerMaster.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RemoteControllerMaster.Database.Models.Machine", b =>
                {
                    b.Property<Guid>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.HasKey("MachineId");

                    b.ToTable("machines", "core");
                });

            modelBuilder.Entity("RemoteControllerMaster.Database.Models.Statistic", b =>
                {
                    b.Property<Guid>("StatisticId")
                        .HasColumnType("uuid")
                        .HasColumnName("statistic_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.HasKey("StatisticId", "Date");

                    b.HasIndex("MachineId");

                    b.ToTable("statistics", "analytics");
                });

            modelBuilder.Entity("RemoteControllerMaster.Database.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.HasKey("UserId");

                    b.ToTable("users", "core");
                });

            modelBuilder.Entity("RemoteControllerMaster.Database.Models.Statistic", b =>
                {
                    b.HasOne("RemoteControllerMaster.Database.Models.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_statistics_machines_machine_id");
                });
#pragma warning restore 612, 618
        }
    }
}
